name: add-issue-to-project
on:
  issues:
    types:
      - opened
permissions:
  contents: read

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.OBS_DOCS_AUTOMATION_PRIVATE_KEY }}
          APP_ID: 203735
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectV2ItemById(input:{projectId:$projectid contentId:$contentid}) {
                item {
                  ... on ProjectV2Item {
                    id
                  }
                }
              }
            }
          projectid: ${{ env.PROJECT_ID }}
          contentid: ${{ github.event.issue.node_id }}
        env:
          PROJECT_ID: "PVT_kwDOAGc3Zs0iZw"
          GITHUB_TOKEN: ${{ steps.get_token.outputs.app_token }}